from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_THEME = FILES_DIR / 'icon.png'

#Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
DEFAULT_TXT_MARGIN = 15
MINIMUN_WIDHT = 600
MINIMUN_BTN_W = 75
MINIMUN_BTN_H = 75

#Colors
PRIMARY_COLOR = '#a37cfd'
PRIMARY_COLOR_DARK_ONE  = "#916ee1"
PRIMARY_COLOR_DARK_TWO = '#6d53a9'